import React from 'react';
import { render } from 'react-dom';
import { Provider } from "react-redux";
import store from "./Redux/store";
import App from './App';
import "./App.css";
import * as serviceWorkerRegistration from './serviceWorkerRegistration';
import reportWebVitals from './reportWebVitals';
render(<Provider store={store}><App /></Provider>,document.getElementById('root'));
serviceWorkerRegistration.register();reportWebVitals();